### ISSUE TITLE
What commmands can take advantage of the list syntax?

### ISSUE THREAD

**Issue by deinspanjer** [wallix/awless-templates#3]
I was trying to figure out how I could delete a list of snapshots by ID.
I tried the following, and it seemed to be valid syntax, but threw an InvalidParameterValue:
`awl -p dre delete snapshot id="[snap-b486e3d6, snap-f2a95a98, snap-4ce83801, snap-51598f22, snap-21fa374f, snap-5d02ce33, snap-63be362a, snap-2239e147, snap-bffaf0f3, snap-51a0b41d, snap-c02bafb0, snap-b7bab2fe, snap-109d316c, snap-c346a48d, snap-acbcd1ae, snap-feb2fcff, snap-bbb7bbba, snap-ff67d3fe, snap-e1662997, snap-58d3ce4b, snap-8e8ba19a, snap-4f54094f, snap-61aa6876, snap-88bd409f, snap-f4d23616, snap-65d82b70, snap-816ac678, snap-85e2819d, snap-a4b50bce, snap-c067ba20, snap-ad47474b, snap-f6b3510e, snap-3762f7cc, snap-07e5b1e1, snap-777d7990, snap-fe308162, snap-a9ad304f, snap-6bff5cdc, snap-cc4bcb7b, snap-8d61a010, snap-a9d86725, snap-cadfb42d, snap-7920f39b, snap-61d8fee8, snap-fbafe0e3, snap-93c49bf7, snap-8093f26a, snap-a2450316]"`

For now, I'll do it in a bash for loop instead, but it seems like I missed something obvious. :/

**Comment by fxaguessy** [comment]
Hi,
I think this is rather an [awless question](https://github.com/wallix/awless/issues) rather than awless-templates one.

Actually, the syntax you write here seems correct, but it does not mean what you want:
`delete snapshot id="[snap-b486e3d6, snap-f2a95a98]"` means snapshot with id is the exact string `"[snap-b486e3d6, snap-f2a95a98]"`
you might want to write
`delete snapshot id=[snap-b486e3d6, snap-f2a95a98]` or `delete snapshot id=snap-b486e3d6,snap-f2a95a98`, which means with id = an array with two values: "snap-b486e3d6" and "snap-f2a95a98".

**Unfortunately**, AFAIK, **AWS API does not allow to delete multiple snapshots at the same time** in one call, and `awless` is not (yet) capable of expanding the array syntax into multiple calls so **neither of these syntax will work**. 
The arrray notation will work only with a few calls such as `awless stop/delete instance`, see awless stop instance -h` for more details.

For now, you will need to do it in bash in a for loop or, for example, with `xargs` if the snapshot ids are found with a listing. See [here](https://github.com/wallix/awless/issues/91) for a working example.

**Comment by deinspanjer** [comment]
Thank you very much for the answer. :)
